export const styles = {
  page: {
    fontFamily: "Arial",
    padding: 20,
    minHeight: "100vh",
    background: "linear-gradient(135deg, #a18cd1, #fbc2eb, #ffecd2, #fcb69f)",
  },
  title: {
    textAlign: "center",
    color: "#3a2c5a",
    marginBottom: 25,
    fontSize: "34px",
    fontWeight: "bold",
  },
  container: { display: "flex", gap: 20 },
  column: {
    flex: 1,
    padding: 15,
    borderRadius: 20,
    background: "rgba(255,255,255,0.8)",
    backdropFilter: "blur(12px)",
    boxShadow: "0 10px 30px rgba(0,0,0,0.15)",
  },
  filters: { textAlign: "center", marginBottom: 20 },
  select: {
    padding: 10,
    borderRadius: 12,
    border: "none",
    background: "white",
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
    cursor: "pointer",
  },
  card: {
    padding: 12,
    marginTop: 12,
    borderRadius: 15,
    background: "linear-gradient(135deg, #f6d365, #fda085)",
    boxShadow: "0 6px 15px rgba(0,0,0,0.1)",
  },
  cardDone: {
    padding: 12,
    marginTop: 12,
    borderRadius: 15,
    background: "linear-gradient(135deg, #c3cfe2, #e0c3fc)",
    boxShadow: "0 6px 15px rgba(0,0,0,0.1)",
  },
  doneText: { textDecoration: "line-through", color: "#6a4c93" },
  completeBtn: {
    marginTop: 10,
    background: "linear-gradient(135deg, #ff9a9e, #fecfef)",
    color: "#4a2e2e",
    border: "none",
    padding: "8px 14px",
    borderRadius: 20,
    cursor: "pointer",
    fontWeight: "bold",
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    transition: "all 0.2s ease",
  },
  undoBtn: {
    marginTop: 10,
    background: "linear-gradient(135deg, #a18cd1, #fbc2eb)",
    color: "#3a2c5a",
    border: "none",
    padding: "8px 14px",
    borderRadius: 20,
    cursor: "pointer",
    fontWeight: "bold",
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    transition: "all 0.2s ease",
  },
};